### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by SteButler**
quite a few fixes. some good (BC Math stuff), some a little bit dirty that may need some attention...sorry!

### CODE REVIEW

**Comment by SteButler** [comment]
urgh, the diff on this looks terrible, white space lines are all deleted and added. ..not quite sure why.

**Comment by Xenland** [comment]
I'll have to take some time to clone and check it out by a whole file basis, generally i didn't want to use bcmath because there is no need to when your doing math with integers. If we allowed float/decimal math or even huge integers then this might be a different story, the acid test will tell you if your computer can support lets say 21million bitcoins as satoshi so a 21trillion representation acid test.

**Comment by SteButler** [comment]
I definitely had some problems without bcmath..let me dig out the test...

this is my first time using git. if there's a better way to do this, let me know.

```
$output["balance_in_satoshi"] = (int) 0; //Integers only
$output["balance_in_bitcoin"] = (double) 0.00000000; //Decimal/Float/Double (THIS IS FOR ONLY DISPLAYING THE TOTAL RECEIVED BALANCE IN BITCOIN , NOT FOR DOING MATH AGAINST!!! Do math in satoshi only)

$tmp_total_received_in_bitcoin = "0.0715"; //this would come directly from bitcoind

$output["balance_in_bitcoin"] = (double) $tmp_total_received_in_bitcoin;
$output["balance_in_satoshi"] = (int) floor($tmp_total_received_in_bitcoin * 100000000); //Convert Bitcoins to satoshi so we can do math with integers.

$output["balance_in_satoshiBC"] = (int) floor(bcmul($tmp_total_received_in_bitcoin,100000000)); //Convert Bitcoins to satoshi so we can do math with integers.

var_dump($output);
```

```
array (size=3)
  'balance_in_satoshi' => int 7149999
  'balance_in_bitcoin' => float 0.0715
  'balance_in_satoshiBC' => int 7150000
```

When you encounter the line with rtrim - i'm sorry for that..its horrible, but for some reason, I was getting standard notation results back from bitcoind on very small satoshi numbers (only on one system though), and couldn't see why - so had to make sure it was always coming back as a usable number. (if it happened to me, it might happen to someone else..?)

**Comment by Xenland** [comment]
See if you can compare satoshi integers from directly from the Bitcoin client instead of comparing the float to the integers, if you could display to me an equal comparison of integers It would prove to me and everyone else this should be required.

**Comment by Xenland** [comment]
I could be wrong but in this case that you showed me, it could be due to a repeating decimal that makes one think that 7149999 is really 0.0715 which it is but with exact precision it could really be 0.07149999_repeating which in integer form it should be 7149999 instead of 7150000 representation.

**Comment by SteButler** [comment]
I'm not really sure what you mean..the value in the account was exactly 7150000 satoshi, or 0.0715 bitcoins (which is the value returned from bitcoind) - as far as im aware, you cant get satoshi values directly from bitcoin? (or have I missed something quite fundamental?)

**Comment by Xenland** [comment]
I wrote that when i was quite tired, Just ignore my solution post last time. So the issue at hand is i need to research bc again as I remember having issues with accounting for satoshi integers and getting weird results and when i didn't use bc math on my shop it worked fine. As far getting the satoshi value from an address, I don't think its possible with out paging through the list transactions command so i was only half correct on that one. So there are some options i need to look over when i have the time. Your welcome to input as always too :)

**Pull request closed without merging**
